env: flex
runtime: nodejs

runtime_config:
  operating_system: "ubuntu22"

service: default
instance_class: F2

automatic_scaling:
  min_num_instances: 1

handlers:
  - url: /.*
    secure: always
    script: auto
