env: standard
runtime: nodejs20
instance_class: F2

service: default

handlers:
  - url: /.*
    secure: always
    script: auto

  - url: /_ah/warmup
    static_files: build/index.html
    upload: build/index.html

inbound_services:
- warmup
automatic_scaling:
  min_instances: 1
